# ref link: https://alinex.gitlab.io/env/mkdocs/
#===================================================================================#
# Site Information
#===================================================================================#
site_name: Phaten Technology|Wi-Fi IOT Module|Wi-Fi IOT Program|Wi-Fi Matter Program
site_description: Shenzhen Phaten Technology Co., Ltd-Phaten Technology|Wi-Fi IOT Module|Wi-Fi IOT Program|Wi-Fi Matter Program
site_author: Phaten
site_dir: '../../site/en'
copyright: Copyright &copy; 2024 <a href="https://www.phaten.com">Shenzhen Phaten Technology Co., Ltd</a>

#===================================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#===================================================================================#
theme:
  name: material
  custom_dir: material
  language: en
  #logo: assets/images/logos/binbash-icon.png
  # icon: # https://www.materialpalette.com/icons
  logo: assets/images/logos/phaten-logo-cn.png
  favicon: assets/images/logos/phaten-logo-ico.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.top
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      #primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      #primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: true
       caption_position: bottom
       background: white
       shadow: true

extra_css:
    - assets/stylesheets/extra.css

extra_javascript:
    - assets/javascripts/extra.js

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  alternate:
    # Switch to English
    - name: English
      #link: https://leverage.binbash.co
      link: /en/
      lang: en

    # Switch to Chinese
    - name: 中文
      #link: https://leverage.binbash.co/zh/
      link: /zh/
      lang: zh

#===================================================================================#
# Mkdocs Markdown Extentions, Plugins & extras
#===================================================================================#
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __spanpymdownx.tilde
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path:
        - docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - Home: index.md
  - Applications:
    - solutions/index.md
    - IoT Pass-through Solutions:
        - RTL8720DF Wi-Fi 5.8G Data Pass-through Application for Automotive VR Solution: solutions/8720df/vr_glasses_solution.md
        - RTL8720CF General Pass-through Solution: solutions/8720cf/rtl8720cf_solution.md
    - Matter Pre-Burn DAC Module Application Solution: solutions/matter/Pre_Burn_DAC_Module.md
    - Matter Application Solutions: 
        - solutions/matter/index.md
        - ESP8684 Matter 1-5 Socket Application Solution: solutions/matter/socket1_5.md
        - ESP8684 Matter 5-Lamp Application Solution: solutions/matter/rgbcw_light.md
    - Tasmota  Preset Application Solutions:
        - solutions/tasmota/index.md
        - Preset Tasmota Power Meter Socket Application Solution: solutions/tasmota/socket.md
        - Preset Tasmota-matter Socket Application Solution: solutions/tasmota/tasmota-matter.md
        - Preset Tasmota-matter 5-Lamp Application Solution: solutions/tasmota/tasmota-matter-light.md
    

  - Product Center:
    - products/index.md
    - Module:
      - RTL8720DF:
        - W5B03A-1720DFV1: products/8720df/W5B03A-1720DFV1.md
      - RTL8720CF:
        - WBR3DU-C: products/8720cf/WBR3DU-C.md
      - ESP8684: 
        - WB02A-8684H2V1: products/matter/socket1_5.md
        - WB03A-8684H2V1: products/matter/WB03A-8684H2V1.md
        - WB02B-8684H2V1: products/matter/WB02B-8684H2V1.md
      - ESP8685: 
        - WB02A-8685H4V1: products/tasmota/tasmota-matter.md

    - Development board:
        - NodeMcu-8720DFV1 Development board: products/8720df/dev_board.md
    - Serial board: products/serial_board.md

  - Documentation:
    - dev_doc/index.md
    - Matter:
      - Matter Accreditation: dev_doc/matter/matter_certification.md
    - Tasmota:
      - Introduction to Tasmota: dev_doc/tasmota/getting_started.md
    - Module:
      - RTL8720DF:
        - W5B03A-1720DFV1: services_support/8720df/W5B03A-1720DFV1_datasheet.md
      - RTL8720CF:
        - WBR3DU-C: services_support/8720cf/WBR3DU-C_datasheet.md
      - ESP8684:
        -  WB02A-8684H2V1: services_support/matter/WB02A-8684H2V1_datasheet.md
        -  WB03A-8684H2V1: services_support/matter/WB03A-8684H2V1_datasheet.md
        -  WB02B-8684H2V1: services_support/matter/WB02B-8684H2V1_datasheet.md
      - ESP8685:
        -  WB02A-8685H4V1: services_support/tasmota/WB02A-8685H4V1_datasheet.md
    # - Development board:
    #   - NodeMcu-8720DFV1 Development board: dev_doc/8720df/dev_board.md


  - Sample purchase:
    - buy_sample/index.md
    - Module: buy_sample/model.md
    - Development board: buy_sample/8720df.md
    - Serial board: buy_sample/serial_board.md

  - Services & Support:
    - services_support/index.md
    - Download Center:
      - RTL8720DF: 
        - download/8720df/index.md
      - RTL8720CF: 
        - download/8720cf/index.md 
      - Tools and Software Downloads: 
        - download/tools_software/index.md
      # - Standard Book: download/8720df/8720df_datasheet.md
    - Frequently Asked Questions: 
      - faq/index.md
      # - XMOS USB audio 驱动说明: faq/xmos_usb_audio_driver.md
    - Inquiries and services:
      - acquire_services/index.md


  - Technical articles:
    - blog/index.md
    # - Matter Product Networking Guide: blog/matter/matter_networking.md


  - About Us:
      - about_us/index.md
      - Join Us: about_us/join_us.md
      - Contact Us: about_us/contact_us.md