# ref link: https://alinex.gitlab.io/env/mkdocs/
#===================================================================================#
# Site Information
#===================================================================================#
site_name: 飞腾云科技|Wi-Fi IOT模组|Wi-Fi IOT方案|Wi-Fi Matter方案
site_description: 深圳市飞腾云科技有限公司-飞腾云科技|Wi-Fi IOT模组|Wi-Fi IOT方案|Wi-Fi Matter方案
site_author: Phaten
site_dir: '../../site/zh'
copyright: Copyright &copy; 2024 <a href="https://www.phaten.com">深圳市飞腾云科技有限公司</a>

#===================================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#===================================================================================#
theme:
  name: material
  custom_dir: material
  language: en
  #logo: assets/images/logos/binbash-icon.png
  # icon: # https://www.materialpalette.com/icons
  logo: assets/images/logos/phaten-logo-cn.png
  favicon: assets/images/logos/phaten-logo-ico.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.top
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      #primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      #primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: true
       caption_position: bottom
       background: white
       shadow: true

extra_css:
    - assets/stylesheets/extra.css

extra_javascript:
    - assets/javascripts/extra.js

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  alternate:
    # Switch to English
    - name: English
      #link: https://leverage.binbash.co
      link: /en/
      lang: en

    # Switch to Chinese
    - name: 简体中文
      #link: https://leverage.binbash.co/zh/
      link: /zh/
      lang: zh

#===================================================================================#
# Mkdocs Markdown Extentions, Plugins & extras
#===================================================================================#
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __spanpymdownx.tilde
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path:
        - docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - 首页: index.md
  - 应用方案:
    # - 麦克风阵列:
    #   - solutions/mic_array_solution/index.md
    #   - XU316 7MIC无感本地扩音方案: solutions/mic_array_solution/phaten_xu316-la_7mic_solution.md
    # - USB HiFi声卡:
    #   - solutions/hifi_audio/index.md
    #   - XU316 USB多路高清音频解码器方案: solutions/hifi_audio/phaten_xu316_hifi_audio_solution.md
    #- W5B03A-1720DFV1模组: 
      # - solutions\8720df\index.md
    - RTL8720DF 5.8G透传应用方案: solutions/8720df/vr_glasses_solution.md
    #- W5B03A-1720CFV1模组:
    - RTL8720CF 透传应用方案: solutions/8720cf/rtl8720cf_solution.md
    - 飞腾云 Matter应用方案: 
        - solutions/matter/index.md
        - Matter1-5路插座应用方案: solutions/matter/socket1_5.md
        - Matter5路灯应用方案: solutions/matter/rgbcw_light.md
    - 飞腾云 Tasmota应用方案:
        - solutions/tasmota/index.md
        - Tasmota电量计量插座应用方案: solutions/tasmota/socket.md
        - Tasmota-matter插座应用方案: solutions/tasmota/tasmota-matter.md
        - Tasmota-matter5路灯应用方案: solutions/tasmota/tasmota-matter-light.md
    
  # - XMOS USB 高清降噪麦克风系列方案: try-leverage/leverage-project-setup.md
  - 产品中心:
    # - products/index.md
    # - 例子最后请删除--麦克风阵列:
    #     - FTXU316-LA-7MIC-V1:
    #       - products/array_mic/ftxu316_la_7mic_v1_pcba/index.md
    # - USB HiFi声卡:
    #     - A316_1926V1 USB多路音频解码器模组: 
    #       - products/hifi_audio/a316_1926v1/index.md
    - W5B03A-1720DF模组: 
      - products/8720df/index.md
    - WBR3DU-C模组: 
      - products/8720cf/index.md
    - Matter产品: 
      # - products/matter/esp32c2/index.md
      - Matter模组: products/matter/socket1_5.md
      # - Matter5路球泡灯模组: products/matter/rgbcw_light.md
    - Tasmota产品: 
      # - products/tasmota/index.md
      - Tasmota电量计量插座模组: products/tasmota/socket.md
      - Tasmota-matter模组: products/tasmota/tasmota-matter.md
  - 开发文档:
    # - dev_doc/index.md
    - Matter:
      - dev_doc/matter/index.md
      - 使用SDK进行开发: dev_doc/matter/sdk_development.md
      - Matter认证: dev_doc/matter/matter_certification.md
      - 生产注意事项: dev_doc/matter/production_notes.md
    - Tasmota:
      - dev_doc/tasmota/index.md
      - 开始: dev_doc/tasmota/getting_started.md
      - 命令: dev_doc/tasmota/commands.md
      - 编译: dev_doc/tasmota/compile.md
      # - 模组及PCBA: 
      #   - FTXU316-LA-7MIC-V1套件:
      #   - dev_doc/array_mic/ftxu316_la_7mic_v1/index.md
      #   - PCBA套件硬件规格书: dev_doc/array_mic/ftxu316_la_7mic_v1/硬件规格书.md
      #   - 成品及评估板安装使用说明: dev_doc/array_mic/ftxu316_la_7mic_v1/使用说明.md

    # - USB HiFi声卡:
    #   - 开发及评估板:
    #     - XMOS XU316 USB多声道音频评估板: 
    #       - dev_doc/hifi_audio/xk_audio_316_mc_ab/index.md
    #     - PBAX316-90108MV1评估板: 
    #       - dev_doc/hifi_audio/pbax316_90108mv1/index.md
    #       - 评估板硬件规格书: dev_doc/hifi_audio/pbax316_90108mv1/硬件规格书.md
    #       - 评估板使用说明: dev_doc/hifi_audio/pbax316_90108mv1/使用说明.md
    #       - 评估板测试指标: dev_doc/hifi_audio/pbax316_90108mv1/测试指标.md
    #   - 模组及PCBA: 
    #     - A316-1926V1:
    #       - dev_doc/hifi_audio/a316_1926v1/index.md
  - 样品购买:
    # - buy_sample/index.md
    - Matter产品:
      - Matter模组: buy_sample/matter/socket1_5.md
      # - Matter5路球泡灯模组: buy_sample/matter/rgbcw_light.md   通用模组，在插座中就可查看到
    - Tasmota产品: 
      - Tasmota电量计量插座模组: buy_sample/tasmota/socket.md
      - Tasmota-matter模组: buy_sample/tasmota/tasmota-matter.md
    - W5B03A-1720DF模组: buy_sample/8720df.md
    - WBR3DU-C模组: buy_sample/8720cf.md

  - 服务&支持:
    # - services_support/index.md
    - 下载中心:
      # - 工具和软件: 
      #   - download/tools_software/index.md
      # - 产品设计资料: 
      #   - download/product_resource/index.md
      - W5B03A-1720DF资料: 
        - W5B03A-1720DF开发资料: 
          - download/8720df/index.md
        - W5B03A-1720DF模组硬件规格书: download/8720df/8720df_datasheet.md
      - WBR3DU-C资料: 
        - WBR3DU-C开发资料: 
          - download/8720cf/index.md 
        - WBR3DU-C模组硬件规格书: download/8720cf/8720cf_datasheet.md
      - Matter产品资料: 
        - Matter模组硬件规格书: download/matter/socket1_5_datasheet.md
      - Tasmota产品资料:
        - Tasmota电量计量插座模组硬件规格书: download/tasmota/socket_datasheet.md
        - Tasmota-matter模组硬件规格书: download/tasmota/tasmota-matter_datasheet.md
    - 常见问题: 
      - faq/index.md
      # - XMOS USB audio 驱动说明: faq/xmos_usb_audio_driver.md
    - 咨询及服务:
      - acquire_services/index.md


  - 技术文章:
    - blog/index.md
    - Matter产品配网指导: blog/matter/matter_networking.md


  - 关于我们:
      - about_us/index.md
      - 加入我们: about_us/join_us.md
      - 联系我们: about_us/contact_us.md