# ref link: https://alinex.gitlab.io/env/mkdocs/
#===================================================================================#
# Site Information
#===================================================================================#
site_name: 飞腾云科技|Wi-Fi IOT模组|Wi-Fi IOT方案|Wi-Fi Matter方案
site_description: 深圳市飞腾云科技有限公司-飞腾云科技|Wi-Fi IOT模组|Wi-Fi IOT方案|Wi-Fi Matter方案
site_author: Phaten
site_dir: '../../site/zh'
copyright: Copyright &copy; 2024 <a href="https://www.phaten.com">深圳市飞腾云科技有限公司</a>

#===================================================================================#
# Mkdocs Theme (Material Mkdocs) + Extras
#===================================================================================#
theme:
  name: material
  custom_dir: material
  language: en
  #logo: assets/images/logos/binbash-icon.png
  # icon: # https://www.materialpalette.com/icons
  logo: assets/images/logos/phaten-logo-cn.png
  favicon: assets/images/logos/phaten-logo-ico.png
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tabs
    - navigation.top
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      #primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      #primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: material/library

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: true
       caption_position: bottom
       background: white
       shadow: true

extra_css:
    - assets/stylesheets/extra.css

extra_javascript:
    - assets/javascripts/extra.js

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  alternate:
    # Switch to English
    - name: English
      #link: https://leverage.binbash.co
      link: /en/
      lang: en

    # Switch to Chinese
    - name: 简体中文
      #link: https://leverage.binbash.co/zh/
      link: /zh/
      lang: zh

#===================================================================================#
# Mkdocs Markdown Extentions, Plugins & extras
#===================================================================================#
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __spanpymdownx.tilde
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path:
        - docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


#===================================================================================#
# Mkdocs Navigation Tree
#===================================================================================#
nav:
  - 首页: index.md
  - 应用方案: 
    - solutions/index.md

    - AU316Wi-Fi5.8G 7.1.2无线音响方案:
        - solutions/speaker/index.md

    - IOT透传方案: 
        - solutions/iot_passthrough/index.md
        - ESP-AT 透传固件方案: solutions/iot_passthrough/esp-AT.md
        - RTL8720DF Wi-Fi 5.8G数据透传应用于汽车VR方案: solutions/8720df/vr_glasses_solution.md
        - RTL8720CF 通用透传方案: solutions/8720cf/rtl8720cf_solution.md
    
    - Matter 应用方案: 
        - solutions/matter/index.md
        - Matter预烧录DAC模组应用方案: solutions/matter/Pre_Burn_DAC_Module.md
        - ESP8684 Matter通断器应用方案: solutions/matter/circuit_breaker.md
        - ESP8684 Matter1-4路插座应用方案: solutions/matter/socket1_5.md
        - ESP8684 Matter5路灯应用方案: solutions/matter/rgbcw_light.md
        - 8720DF Matter 1-5路插座应用方案: solutions/matter/8720df_matter_socket.md
        - 8720DF Matter 5路灯应用方案: solutions/matter/8720df_matter_light.md

    - Tasmota 预置应用方案:
        - solutions/tasmota/index.md
        - 预置Tasmota电量计量插座应用方案: solutions/tasmota/socket.md
        - 预置Tasmota-matter插座应用方案: solutions/tasmota/tasmota-matter.md
        - 预置Tasmota-matter5路灯应用方案: solutions/tasmota/tasmota-matter-light.md
    # - 解决方案:
    #     - 数据透传:
    #         - RTL8720DF: solutions/8720df/vr_glasses_solution副本.md
    #     - 智能插座: 
    #         - Matter1-5路插座: solutions/matter/socket1_5副本.md
    #     - 氛围灯: 
    #         - Matter5路灯: solutions/matter/rgbcw_light副本.md

  # - XMOS USB 高清降噪麦克风系列方案: try-leverage/leverage-project-setup.md
  - 产品中心: 
    - products/index.md
    - 模组:
      - products/model/index.md
      - RTL8711DCM:
        - WB30D-1711DCMV1: products/model/RTL8711.md
      # - RTL8772Gx:
      - RTL8720DF:
        # - products/8720df/index.md
        - W5B03A-1720DFV1: products/8720df/W5B03A-1720DFV1.md
      - RTL8720CF:
        - WBR3DU-C: products/8720cf/WBR3DU-C.md
      - ESP8684: 
        - WB02A-8684H2V1: products/matter/socket1_5.md
        - WB03A-8684H2V1: products/matter/WB03A-8684H2V1.md
        - WB02B-8684H2V1: products/matter/WB02B-8684H2V1.md
      - ESP8685: 
        # - Tasmota WB02A-8685H4V1: products/tasmota/socket.md
        - WB02A-8685H4V1: products/tasmota/tasmota-matter.md
      # - Matter产品: 
      #   - products/matter/esp32c2/index.md
      #   - Matter模组: products/matter/socket1_5.md
        # - Matter5路球泡灯模组: products/matter/rgbcw_light.md 
      # - Tasmota产品: 
      #   - products/tasmota/index.md
      #   - Tasmota电量计量插座模组: products/tasmota/socket.md
      #   - Tasmota-matter模组: products/tasmota/tasmota-matter.md
    - 开发板:
      - products/dev_board/index.md
      - WB30D-1711DCMV1开发板: products/dev_board/RTL8711dev_board.md
      - NodeMcu-8720DFV1开发板: products/8720df/dev_board.md

    - 串口板: products/serial_board.md

      
  - 开发文档:
    - dev_doc/index.md
    - Matter:
      - Matter认证: dev_doc/matter/matter_certification.md
    - Tasmota:
      - Tasmota入门: dev_doc/tasmota/getting_started.md
      - TasmotaTasmota 常用功能介绍: dev_doc/tasmota/tasmota4.md
      - Tasmota连接Home Assistant: dev_doc/tasmota/tasmota2.md
      - Tasmota连接Amazon的Alexa: dev_doc/tasmota/tasmota3.md

    - 模组: 
      # - dev_doc/modle/modle_index.md
      - RTL8711DCM:
        - WB30D-1711DCMV1: dev_doc/modle/dev_RTL8711.md
      - RTL8720DF:
        - W5B03A-1720DFV1: services_support/8720df/W5B03A-1720DFV1_datasheet.md
      - RTL8720CF:
        - WBR3DU-C: services_support/8720cf/WBR3DU-C_datasheet.md
      - ESP8684:
        -  WB02A-8684H2V1: services_support/matter/WB02A-8684H2V1_datasheet.md
        -  WB03A-8684H2V1: services_support/matter/WB03A-8684H2V1_datasheet.md
        -  WB02B-8684H2V1: services_support/matter/WB02B-8684H2V1_datasheet.md
      - ESP8685:
        -  WB02A-8685H4V1: services_support/tasmota/WB02A-8685H4V1_datasheet.md

    - 无线音响套装:
#        - 2.1 无线音响接线说明: services_support/audio/2.1audio.md
#        - 5.1 无线音响接线说明: services_support/audio/5.1audio.md
#        - 7.1 无线音响接线说明: services_support/audio/7.1.2audio.md
      - 使用说明: services_support/audio/used.md
      - RTL8711DCM 模组设计说明: services_support/audio/RTL8711model.md
      - RTL8711DCM 演示板接线说明: services_support/audio/RTL8711dome.md

  - Tasmtoa:
    - Tasmota-OTA: download/tasmota-ota/index.md

  - 样品购买:
    - buy_sample/index.md
    - 模组: buy_sample/model.md
    - 开发板: buy_sample/8720df.md
    - 串口板: buy_sample/serial_board.md


  - 服务&支持:
    - services_support/index.md
    - 下载中心:
      - RTL8720DF: 
        - download/8720df/index.md
      - RTL8720CF: 
        - download/8720cf/index.md
      - ESP-AT:
        - download/esp-at/index.md
        - 固件: download/esp-at/firmware.md
      # - 工具和软件下载: 
      #   - download/tools_software/index.md
      # - 规格书: download/8720df/8720df_datasheet.md

    - 常见问题: 
      - faq/index.md
      # - XMOS USB audio 驱动说明: faq/xmos_usb_audio_driver.md
    - 咨询及服务: 
      - acquire_services/index.md


  - 技术文章:
    - blog/index.md
    # - Matter产品配网指导: blog/matter/matter_networking.md


  - 关于我们:
      - about_us/index.md
#      - 加入我们: about_us/join_us.md
      - 联系我们: about_us/contact_us.md